version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: postgres-travel-db
    environment:
      POSTGRES_DB: travel_expense_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - jglm-184_data:/var/lib/postgresql/data

volumes:
  jglm-184_data: