app:
  jwt:
    public-key: ${JWT_PUBLIC_KEY:classpath:app.pub}
    private-key: ${JWT_PRIVATE_KEY:classpath:app.key}

spring:
  application:
    name: travel-expense-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/travel_expense_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key: ${app.jwt.public-key}
          private-key: ${app.jwt.private-key}